server:
  port: 8080

spring:
  config:
    import: application-common.yml
  data:
    mongodb:
      database: challenger
      authentication-database: admin
      uri: mongodb://admin:admin@challenger_mongo:27017
      auto-index-creation: true