name: Challenger
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - develop

jobs:

  unit-tests:
    name: Maven test phase

    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout data
        uses: actions/checkout@v3

      - name: Corretto install
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Java version
        run: |
          echo "######### CORRETTO VERSION #########"
          java -version
          echo "####################################"

      - name: Maven setup
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 17
          maven-version: 3.8.6

      - name: Maven version
        run: |
          echo "########## MAVEN VERSION ###########"
          mvn -version
          echo "####################################"      

      - name: Set General env
        run: |
          echo "################# STORAGE SERVICE ENV ##################"
          echo "SS_APP_NAME=storage-service" >> $GITHUB_ENV
          echo "SS_PORT=80" >> $GITHUB_ENV
          echo "########################################################"     

      - name: Common module install
        working-directory: ./common
        run: |
          mvn clean install  

      - name: Storage service testing
        working-directory: ./${{ env.SS_APP_NAME }}
        run: |
          mvn test

  sonar-qube:
    name: Sonar qube phase
    needs: [ unit-tests ]

    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout data
        uses: actions/checkout@v3

      - name: Corretto install
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Java version
        run: |
          echo "######### CORRETTO VERSION #########"
          java -version
          echo "####################################"

      - name: Maven setup
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 17
          maven-version: 3.8.6

      - name: Maven version
        run: |
          echo "########## MAVEN VERSION ###########"
          mvn -version
          echo "####################################"
        
      - name: SonarCloud Scan
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  service-building:
    name: Maven package phase
    needs: [ sonar-qube ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout data
        uses: actions/checkout@v3

      - name: Corretto install
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Java version
        run: |
          echo "######### CORRETTO VERSION #########"
          java -version
          echo "####################################"

      - name: Maven setup
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 17
          maven-version: 3.8.6

      - name: Maven version
        run: |
          echo "########## MAVEN VERSION ###########"
          mvn -version
          echo "####################################"      

      - name: Set General env
        run: |
          echo "################# STORAGE SERVICE ENV ##################"
          echo "SS_APP_NAME=storage-service" >> $GITHUB_ENV
          echo "SS_PORT=80" >> $GITHUB_ENV
          echo "########################################################"     

      - name: Common module install
        working-directory: ./common
        run: |
          mvn clean install  

      - name: Storage service build
        working-directory: ./${{ env.SS_APP_NAME }}
        run: |
          mvn package
    
